### ISSUE TITLE
PIANO COMP-EX-UNO

### ISSUE THREAD

**Issue by grammaton** [PMNAZARETH/2016#11]
Dal suono di [pianoforte sintetizzato](https://github.com/PMNAZARETH/2016/blob/master/CSOUND/SinePianoEmulator_3.csd) elabora un progetto compositivo (semplice) che esponga un progressivo deterioramento della percezione di *suono di pianoforte* verso altro.

Regole:
- Il contenuto armonico non deve variare
- Le parziali possono variare in durata, intensità (e quindi anche forma di inviluppo) e momento di attacco

**Comment by mariocroce** [comment]
Il contrasto tra gli opposti è ciò che determina il mondo in quanto tale.
ogni oggetto, idea, comportamento o attitudine acquisisce significato in relazione al suo contrario.
il bene e il male; il semplice e il complesso; la razionalità e la follia: sono queste alcune delle contrapposizioni che alimentano il nostro mondo e il nostro pensiero coesistendo e collaborando da sempre.
Ho tentato di realizzare un oggetto sonoro in contrapposizione col suono di pianoforte che lo genera, stravolgendo le parziali che lo formano e tentando così di darne una visione antitetica ma familiare.
