### ISSUE TITLE
MaxMsp Folder

### ISSUE THREAD

**Issue by grammaton** [PMNAZARETH/2016#2]
@mariocroce must:

1. git clone `https://github.com/PMNAZARETH/2016.git`
2. drag `maxmsp` folder into `2016/mariocroce/`
    - `gitmario/PMNAZARETH/2016/mariocroce/maxmsp`
3. `cd 2016` 
4. `git status`
5. `git add .` per aggiungere tutti i file e le nuove cartelle
5. `git commit -am "add maxmsp folder"`
6. `git push`

**Comment by grammaton** [comment]
@mariocroce per fare i box grigi attorno al testo devi utilizzare gli apici singoli che su Mac Os si fanno con `alt+9`

**Comment by mariocroce** [comment]
done

**Comment by grammaton** [comment]
You Rox! 
(Close the issue)

**Comment by grammaton** [comment]
@mariocroce però non hai caricato la cartella… quindi riapro la issue

**Comment by grammaton** [comment]
@mariocroce questo è l'attuale albero delle cartelle:
```
.
├── LICENSE
└── README.md
```
per aggiungere la cartella di maxmsp ti mancava:
`git add .`
